language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx
install: bundle install
before_script:
  - gem build ricojson.gemspec
  - gem install ricojson
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
